version: '3.9'

services:
    nginx:
        image: nginx:1.24-alpine
        ports:
            - '80:80'
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    php-fpm:
        environment:
            PHP_IDE_CONFIG: "serverName=docker"
        build:
            dockerfile: docker/php-fpm/Dockerfile
            context: .
        volumes:
            - ./:/var/www/html
            - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: app
            POSTGRES_USER: app
        ports:
            - '5432:5432'
        volumes:
            - database_data:/var/lib/postgresql/data:rw
    mailer:
        image: yappabe/mailcatcher
        ports:
            - '81:1080'
        tty: true

volumes:
    database_data:
